rebuild_source: @build.live
hooks:
    build: |
      cp sites/default/default.settings.php sites/default/settings.php
      echo "\$databases['default']['default'] = array(
        'driver' => 'mysql',
        'database' => 'drupal',
        'username' => 'drupal',
        'password' => 'drupal',
        'host' => 'database',
      );" >> sites/default/settings.php
      mkdir sites/default/files
      chmod 777 sites/default/files
