<?php

/**
 * Enable the devmaster modules.
 */
function devshop_build_update_7001() {
    module_enable(array(
        'hosting',
        'hosting_task',
        'hosting_server',
        'hosting_site',
        'hosting_platform',
        'devshop_hosting',
        'devshop_dothooks',
        'devshop_projects',
        'devshop_pull',
        'devshop_github',
        'devshop_testing',
        'aegir_ssh',
        'aegir_download',
        'aegir_commit',
        'aegir_features',
    ));
}