<?php
/**
 * @file
 * Code for the DevShop Servers feature.
 */

include_once 'devshop_servers.features.inc';

/**
 * Implements hook_menu();
 * @return mixed
 */
function devshop_servers_menu(){
  $items['keys/%'] = array(
    'page callback' => 'devshop_servers_user_keys',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

function devshop_servers_user_keys($username) {
  $account = user_load_by_name($username);
  $keys = sshkey_load_all_by_entity('user', $account->uid);
    foreach ($keys as $key) {
      print $key->value . PHP_EOL;
    }
}
