<?php
/**
 * @file
 * Code for the DevShop Servers feature.
 */

include_once 'devshop_servers.features.inc';

/**
 * Implements hook_menu();
 * @return mixed
 */
function devshop_servers_menu(){
  $items['keys/%'] = array(
    'page callback' => 'devshop_servers_user_keys',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

function devshop_servers_user_keys($username) {
  $account = user_load_by_name($username);
  $keys = sshkey_load_all_by_entity('user', $account->uid);
    foreach ($keys as $key) {
      print $key->value . PHP_EOL;
    }
}

/**
 * Implements hook_ansible_inventory_alter().
 */
function devshop_servers_ansible_inventory_alter(&$inventory) {
  $inventory->ansible_apache->vars->aegir_user_name = 'devshop';
  $inventory->ansible_apache->vars->aegir_user_uid = 123456;
  $inventory->ansible_apache->vars->aegir_user_home = '/home/devshop';
}

/**
 * Implements hook_node_access_records_alter().
 *
 * Make OG access grants priority over hosting_server/hosting_client.
 */
function devshop_servers_node_access_records_alter(&$grants, $node) {
  // If node has a project and does not have another access realm... load the grants from the project.
  if (!empty($node->project) && $node->type != 'project') {
    $project_nid = is_numeric($node->project)? $node->project: $node->project->nid;
    $project_node = node_load($project_nid);
    $grants = module_invoke_all('node_access_records', $project_node);
  }

  // Give tasks on servers access
  if ($node->type == 'task') {
    $server_node = node_load($node->rid);
    if ($server_node->type == 'server' && isset($server_node->devshop_organization[LANGUAGE_NONE][0]['target_id'])) {
      $grants = module_invoke_all('node_access_records', $server_node);
    }
  }

  // If node is a server task, load grants from the devshop_organization node
//  dsm($node, 'ehko');
//  if ($node->type == 'task' && $node->ref->type == 'server' && isset($node->ref->devshop_organization[LANGUAGE_NONE][0]['target_id'])) {
//    $grants = module_invoke_all('node_access_records', $node->ref);
//  }


  // If node has OG Access, force it to be the only one.
  foreach ($grants as $i => &$grant) {
    if ($grant['realm'] == 'og_access:node') {
      $grant['priority'] = 2;
      $grants = array(
        $grant
      );
      break;
    }
  }

}


/**
 * Implements hook_form_alter().
 */
function devshop_servers_form_server_node_form_alter(&$form, &$form_state, $form_id) {
  $form['title']['#title'] = t('Name your Server');
  $form['title']['#attributes']['placeholder'] = t('servername');
  $form['title']['#attributes']['data-placement'] = 'top';

  $form['title']['#description'] = t('Enter the unique name you wish to give your server.');

  $form['title']['#field_prefix'] = "<div class='input-group'>";
  $form['title']['#field_suffix'] = "
        <div class=\"input-group-addon\">.devshop.systems</div>
        </div>
  ";

  $form['title']['#element_validate'][] = 'devshop_servers_title_element_validate';

  // Remove the domain from title.
  $form['title']['#default_value'] = strtr($form['title']['#default_value'], array(
    '.devshop.systems' => '',
  ));

  // Disable fields
  $form['human_name']['#access'] = FALSE;

  // Hide IP address form on server create.
  if (!isset($form['#node']->nid)){
    $form['ips_wrapper']['#access'] = FALSE;
  }

  $form['field_url']['#access'] = FALSE;
  $form['field_root_server_user']['#access'] = FALSE;

  // @TODO: Test that content privacy is still saved.
  $form['group_content_access']['#access'] = FALSE;

  $form['services_tabs']['#weight'] = 10;

  // Add our own Options selector
  $form['devshop_build_server'] = array(
    '#type' => 'fieldset',
    '#title' => t('Dedicated DevShop Server'),
    '#description' => t('Dedicated DevShop Servers are not virtualized: You are buying bare metal!')
  );
  $label_mini =  <<<HTML
<h3>Mini Dedicated</h3>
<ul>
<li>8GB DDR3 RAM</li>
<li>4 CPU @ 2.4 GHz</li>
<li>80 GB SSD</li>
<li>1Gbps Network </li>
</ul>

HTML;
  $form['devshop_build_server']['mini'] = array(
    '#name' => 'devshop_build_server',
    '#type' => 'radio',
    '#title' => $label_mini,
    '#return_value' => 'mini',
    '#prefix' => '<div class="col-xs-6 col-sm-6">',
    '#suffix' => '</div>',
  );

  $label_mega =  <<<HTML
<h3>Mega Dedicated</h3>
<ul>
<li>32GB DDR3 RAM</li>
<li>4 CPU @ 3.4 GHz</li>
<li>120 GB SSD</li>
<li>2Gbps Network</li>
</ul>
HTML;

  $form['devshop_build_server']['mega'] = array(
    '#name' => 'devshop_build_server',
    '#type' => 'radio',
    '#title' => $label_mega,
    '#return_value' => 'mega',
    '#prefix' => '<div class="col-xs-6 col-sm-6">',
    '#suffix' => '</div>',
  );


}

/**
 * Validator for the server name field: Appends ".devshop.systems" to the title.
 * @param $element
 * @param $form_state
 * @param $form
 */
function devshop_servers_title_element_validate($element, &$form_state, $form) {
  if (!empty($element['#value'])) {
    $new_name = $element['#value'] . '.devshop.systems';
    form_set_value($element, $new_name, $form_state);
  }
}


/**
 * Implements hook_form_alter().
 */
function devshop_servers_form_devshop_project_create_step_git_alter(&$form, &$form_state, $form_id) {

  if (!empty(arg(3))) {
    // Create Project Wizard
    // Add info about connecting to Repo
    $form['connect'] = array(
      '#type' => 'fieldset',
      '#title' => t('Repository Access'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
      '#description' => t('In order to launch copies of your website, devshop.build needs access to your source code.'),
    );
    $form['connect'] ['options'] = array(
      '#theme' => 'item_list',
      '#items' => array(
        t('If your project is on GitHub, add the user !link. If you grant administrator access to devshopbot, will be able to create webhooks for you.', array(
          '!link' => l( '<img src="https://avatars3.githubusercontent.com/u/11931385?v=3&s=16">' .
            t('devshopbot'), 'http://github.com/devshopbot',
            array(
              'html' => TRUE,
              'attributes' => array(
                'class' => 'label label-default',
              ),
            )
          ),
        )),
        t('If your project is on Acquia or Pantheon, add the user !link', array(
          '!link' => '<span class="label label-default"><img src="https://avatars3.githubusercontent.com/u/11931385?v=3&s=16">' . t('build@opendevshop.com') . '</span>'
        )),
        t('If your project is in a private git server, grant access to the devshop.build !modal', array(
          '!modal' => devshop_get_ssh_key_modal(),
        )),
      ),
    );
  }
}

function devshop_get_ssh_key_modal() {

  $ssh_key = variable_get('devshop_public_key', '');

  return <<<HTML
    <button type="button" class="btn label label-default" data-toggle="modal" data-target="#sshKeyModal">
        <i class="fa fa-key"></i>
        SSH Public Key
    </button>
  
    <!-- Modal -->
    <div class="modal fade" id="sshKeyModal" tabindex="-1" role="dialog" aria-labelledby="sshKeyModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="sshKeyModalLabel">
                        DevShop.Build SSH Public Key
                    </h4>
                </div>
                <div class="modal-body">
                    <textarea rows="13" cols="80" onclick="this.select()">$ssh_key</textarea>
                    <p>
                      This SSH public key is used to clone your code. Make sure you have added this key to your repository.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
  

HTML;
}

/**
 * Implements hook_form_alter().
 */
function devshop_servers_form_devshop_remotes_alias_add_form_alter(&$form, &$form_state, $form_id) {

  $form['note']['#markup'] = t('To deploy data from a remote site, make sure you grant DevShop.Build access:');

  $form['options'] = array(
    '#weight' => -9,
    '#theme' => 'item_list',
    '#items' => array(
      t('If your project is on Acquia or Pantheon, add the user !link', array(
        '!link' => '<span class="label label-default"><img src="https://avatars3.githubusercontent.com/u/11931385?v=3&s=16">' . t('build@opendevshop.com') . '</span>'
      )),
      t("If your site is on a private server, you can grant access to devshop.build's SSH key:"),
    ),
  );
}

/**
 * Implements hook_node_presave().
 */
function devshop_servers_node_presave($node) {
  if ($node->type == 'server' && $node->services['ansible_roles']->type == 'devmaster') {
    $node->field_url['und'][0] = array(
      'url' => 'http://' . $node->title,
      'title' => t('Launch DevShop'),
    );
  }
}