<?php
/**
 * @file
 * Code for the DevShop Organizations feature.
 */

include_once 'devshop_organizations.features.inc';

function devshop_organizations_intercomio_settings_alter(&$settings) {

  global $user;
  $account = user_load($user->uid);

  if (isset($account->field_user_organizations['und']) && is_array($account->field_user_organizations['und'])) {
    foreach ($account->field_user_organizations['und'] as $i => $data) {
      $org_node = node_load($data['target_id']);

      if (isset($org_node->nid)) {
        $settings['companies'][] = array(
          'company_id' => $org_node->nid,
          'name' => $org_node->title,
        );
      }
    }
  }

  // If picture, add "avatar" object
  if (isset($user->picture)) {
    $picture = file_load($user->picture);
    if (isset($picture->uri)) {
      $settings['avatar'] = array(
        'type' => 'avatar',
        'image_url' => file_create_url($picture->uri),
      );
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function devshop_organizations_node_insert($node) {
  if (!empty($node->project)) {
    $project_node = node_load($node->project);
    $node->devshop_organization = $project_node->devshop_organization;
    $node->devshop_content_access = $project_node->devshop_content_access;
  }
}

/**
 * Implements hook_menu().
 */
function devshop_organizations_menu() {
  $items['access_denied'] = array(
    'page callback' => 'devshop_build_403',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function devshop_organizations_menu_alter(&$items) {
  $items['node/%node/group']['type'] = MENU_CALLBACK;
}

/**
 * Access denied page.
 *
 * @return string
 */
function devshop_build_403() {

  drupal_set_title(t('Access Denied!'));

  $html = <<<HTML

  <h2>However...</h2>
  <p>DevShop.Build is in private alpha.  Would you like to sign up?</p>
  <p><a href="/contact" class="btn btn-large btn-success">Request Early Access</a></p>
HTML;

  return $html;

}